FROM python:3.12

WORKDIR /app

COPY . .

RUN pip3 install --no-cache-dir -r requirements.txt

ENV FLASK_ENV=production
ENV PORT=3001

EXPOSE 3001

CMD ["gunicorn", "--workers=4", "--bind=0.0.0.0:3001", "app:app"]